{ config, pkgs, ... }:
{
  # Minimal hardware configuration for testing
  # This file should be generated by 'nixos-generate-config'
  # or contain your actual hardware configuration

  # Placeholder configuration
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "sd_mod"
    "rtsx_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Filesystems - configured for your Btrfs setup
  fileSystems."/" = {
    device = "/dev/mapper/luks-04f04b8a-5ddf-4f09-acb6-eb4606b31076";
    fsType = "btrfs";
    options = [
      "noatime"
      "nodiratime"
      "compress=zstd"
      "space_cache=v2"
      "ssd"
      "commit=120"
    ];
  };

  # Swap - adjust according to your system
  swapDevices = [
    # { device = "/dev/sda2"; }  # Uncomment and adjust if you have swap
  ];
}
